FROM php:7.2.12-fpm

RUN apt-get update
RUN apt-get -y install libssl1.1 libpng-dev libxml2-dev zlib1g-dev libssl-dev libpcre3 libpcre3-dev libzip-dev gnupg2 sqlite3 libsqlite3-dev wget libmariadb-dev libmariadb-dev-compat default-mysql-client
RUN docker-php-ext-install gd json mbstring mysqli mysqli pdo pdo_mysql zip pdo_sqlite
RUN pecl install mongodb-1.6.1 && docker-php-ext-enable mongodb && apt-get clean && rm -rf /var/lib/apt/lists/*

# Smartyの解凍とインストール
RUN wget https://github.com/smarty-php/smarty/archive/refs/tags/v2.6.31.tar.gz -O /tmp/smarty.tar.gz \
    && tar -zxf /tmp/smarty.tar.gz -C /usr/local/lib/php \
    && mv /usr/local/lib/php/smarty-2.6.31/libs/* /usr/local/lib/php/ \
    && rm -rf /usr/local/lib/php/smarty-2.6.31 /tmp/smarty.tar.gz

# Smartyの依存関係を解決
RUN pear channel-update pear.php.net
