version: "3.8"
services:
  mysql:
    container_name: rinnai-mysql
    build:
      context: .
      dockerfile: Dockerfile_mysql
    volumes:
      - /docker/mysql/my.cnf:/etc/my.cnf
      - /docker/mysql:/var/lib/mysql
    env_file: ./.env
    ports:
      - 3306:${DB_PORT}
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=${TZ}
    restart: always

  httpd:
    container_name: rinnai-httpd
    build:
      context: .
      dockerfile: Dockerfile_mysql
    volumes:
      - /docker/httpd/rinnai.conf:/etc/httpd/conf/httpd.conf
      - /dokcer/apps/public:/var/www/html
    ports:
      - "80:80"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=${TZ}
    restart: always

  php:
    container_name: rinnai-php
    build:
     context: .
     dockerfile: Dockerfile_php
    volumes:
      - /docker/php/rinnai.conf:/home/homepage/stg_rinnai/app/httpdconf/stg.rinnai.conf
      - /docker/apps:/var/www/html
      - /logs/php-fpm:/var/log/php-fpm
      - /work/dockerfile/:/tmp/
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - db
      - httpd

  perl:
    container_name: rinnai-perl
    build:
     context: .
     dockerfile: Dockerfile_perl
    volumes:
     -  /usr/lib/perl5/5.16.3/CPAN/:/usr/lib/perl5/5.16.3/CPAN/Config.pm
     - /app/src/scripts/:/app/src/scripts/update_sitemap.pl
     - /app/src/lib/:/app/src/lib/RmktFileManager.pm
     - /home/homepage/.cpan/build/Catalyst-Runtime-5.80018-wx8HNu/blib/lib/Catalyst/Controller.pm
     - /home/homepage/.cpan/build/Catalyst-Runtime-5.80018-wx8HNu/lib/Catalyst/Controller.pm
     - /usr/local/lib/perl5/site_perl/5.10.0/Catalyst/Controller.pm
     - /usr/lib/perl5/5.16.3/perl5db.pl
    ports:
     - "5000:5000"
    env_file: ./.env
    depends_on:
     - httpd
     - db
    environment:
     - TZ=${TZ}
     - cpus=0.50
     - mem_limit=768m
                       
