FROM perl:5.16.3

RUN echo y | cpan --force install \
    Catalyst::Controller \
    strict \
    utf8 \
    warinings \
    CGI \
    GD \
    File \
    LWP \
    parent \
    Scalar \
    DBI \
    DBD \
    URI \
    Moose \
    Unicode::RecursiveDowngrade \
    Estraier::Simple \
    Unicode::Japanese \
    HTML::Template \
    HTML::Entities \
    MIME::Base64 \
    Storable \
    JSON::Syck \
    Data::Dumper \
    XML::Atom \
    XML::Simple \
    Data::Dumper

WORKDIR /app/src/scripts/

CMD ["perl", "update_sitemap.pl"]

